language: python
python:
- "3.6"

# command to install dependencies
install:


# command to run tests
script:
- lsblk
- ansible-lint install/*.yml -x 303,701,601,206,602,403,301,502,306 -v
- molecule --version
- ansible --version
- sudo molecule test

